---
# tasks file for ethereum
- name: install stuff to compile geth
  apt: pkg={{ item }} state=installed
  with_items:
    - build-essential
    - libgmp3-dev

- name : download {{ go }}
  get_url: url=https://storage.googleapis.com/golang/{{ go }}.tar.gz dest=/tmp/{{ go }}.tar.gz validate_certs=no

- name: check go extraction
  stat: path=/tmp/{{ go }}
  register: go_extracted

- name: unarchive go
  unarchive: src=/tmp/{{ go }}.tar.gz dest=/opt copy=no
  when: not go_extracted.stat.exists

- name: Clone geth 1.4.10 (no bugs with private network)
  git: repo=https://github.com/ethereum/go-ethereum.git dest=/opt/go-ethereum accept_hostkey=True version=5f55d95

- name: check geth build
  stat: path=/opt/go-ethereum/build/bin/geth
  register: geth_build

- name: make geth
  command: chdir=/opt/go-ethereum make
  environment:
    GOROOT: /opt/go
    GOPATH: /home/vagrant/go
    PATH: /opt/go/bin:{{ ansible_env.PATH }}
  when: not geth_build.stat.exists

- name: add ethereum ppa
  apt_repository: repo='ppa:{{ item }}' update_cache=yes
  with_items:
    - ethereum/ethereum

- name: install solc
  apt: pkg=solc state=installed
