---
# tasks file for ethereum
- name: install stuff to compile geth
  apt: pkg={{ item }} state=installed
  with_items:
    - build-essential
    - libgmp3-dev
    - golang

- name: Clone geth 1.4.5 (no bugs with private network)
  git: repo=https://github.com/ethereum/go-ethereum.git dest=/home/vagrant/go-ethereum accept_hostkey=True version=a269a71
