---
# tasks file for devtools

- name: install common editors via apt (vim/nano/gedit/emacs)
  apt: pkg={{ item }} state=installed
  with_items:
    - vim
    - nano
    - gedit
    - emacs

- name: install common useful devtools(git/tig/htop/meld/curl/wget/gdebi)
  apt: pkg={{ item }} state=installed
  with_items:
    - vim
    - git
    - tig
    - htop
    - meld
    - curl
    - wget
    - gdebi
    - zsh
    - python-pip
    - language-pack-fr

- name: Install virtualenvwrapper
  pip: name=virtualenvwrapper

- name: zsh default shell
  user: name=vagrant shell=/usr/bin/zsh

- name: Get oh-my-zsh from git
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest=/home/vagrant/.oh-my-zsh accept_hostkey=True update=no

- name: Zsh conf
  template: src=zshrc.j2 dest=/home/vagrant/.zshrc owner=vagrant group=vagrant

- name: create .vim directory
  file: dest=/home/vagrant/.vim owner=vagrant group=vagrant state=directory

- name: deploy vimrc
  template: src=vimrc.j2 dest=/home/vagrant/.vim/vimrc owner=vagrant group=vagrant

- name: symlink vimrc
  file: src=/home/vagrant/.vim/vimrc dest=/home/vagrant/.vimrc owner=vagrant group=vagrant state=link

- name: Get vim solidity
  git: repo=https://github.com/tomlion/vim-solidity.git dest=/tmp/vim-solidity accept_hostkey=True update=no

- name: deploy solidity for vim
  copy: src=/tmp/vim-solidity/{{ item }} dest=/home/vagrant/.vim owner=vagrant group=vagrant
  with_items: 
    - indent
    - ftdetect
    - syntax


- name: chown vagrant home dir
  file: dest=/home/vagrant owner=vagrant group=vagrant recurse=yes

